#! /bin/bash
echo "Please select an item"
echo "**************************************"
echo "*   1.   Both 2 & 3                  *"
echo "*   2.   Deploy the blog.            *"
echo "*   3.   Backup the blog's source.   *"
echo "*   4.   Hexo server.                *"
echo "*   *.   Exit.                       *"
echo "**************************************"
read a
hexo clean
cd ./.shell
case $a in
1) sh deploy.sh
    sh push.sh
;;
2) sh deploy.sh
;;
3) sh push.sh
;;
4) hexo s
;;
*) echo "see you"
;;
esac
cd ..
hexo clean
hexo clean